/*
Copyright (c) 2016 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.asset.envtexture;

import std.stdio;

import dlib.core.memory;
import dlib.core.stream;

import dlib.image.image;
import dlib.image.unmanaged;
import dlib.image.io.png;
import dlib.image.resampling.bilinear;
import dlib.image.filters.boxblur;

import dgl.asset.resource;
import dgl.graphics.texture;
import dgl.graphics.material;

class EnvTextureResource: Resource
{
    enum numRougnessLevels = 7;
    SuperImage image;
    SuperImage[numRougnessLevels] blurred;
    UnmanagedImageFactory imageFactory;
    Texture[numRougnessLevels] textures;
    
    this(UnmanagedImageFactory imgfac)
    {
        imageFactory = imgfac;
        //foreach(i; 0..numRougnessLevels)
        //    textures[i] = New!Texture();
        textures[0] = New!Texture();
    }

    bool loadThreadSafePart(InputStream istrm)
    {
        if (image !is null)
            return true;
        
        auto res = loadPNG(istrm, imageFactory);
        image = res[0];
        if (image !is null)
        {
        /*
            blurred[0] = image;
            uint w = image.width;
            uint h = image.height;
            foreach(i; 1..numRougnessLevels)
            {
                w = image.width / (i + 4);
                h = image.height / (i + 4);
                auto resampled = resampleBilinear(image, w, h);
                blurred[i] = resampled.createSameFormat(w, h);
                boxBlur(resampled, blurred[i], i); // TODO: use special seamless blur
                Delete(resampled);
            }
        */
            return true;
        }
        else
        {
            writeln(res[1]);
            return false;
        }
    }
    
    bool loadThreadUnsafePart()
    {
    /*
        foreach(i; 0..numRougnessLevels)
        {
            if (blurred[i] !is null)
            {
                textures[i].createFromImage(blurred[i]);
                //textures[i].filtering = false;
                Delete(blurred[i]);
                blurred[i] = null;
                if (!textures[i].valid)
                    return false;
            }
            else
                return false;
        }
    */
        textures[0].createFromImage(image);
        Delete(image);
        return true;
    }
    
    void applyToMaterial(Material m)
    {
    /*
        float r = m.roughness * 10.0f;
        if (r < 0) r = 0;
        if (r > 9) r = 9;
        float v = cast(float)numRougnessLevels / 10.0f;
        r *= v;
        uint i = cast(uint)r;
        m.textures[3] = textures[numRougnessLevels-1];
        m.textures[4] = textures[i];
    */
        m.textures[3] = textures[0];
        m.textures[4] = textures[0];
    }
    
    ~this()
    {
    /*
        foreach(i; 0..numRougnessLevels)
        {
            if (blurred[i] !is null)
                Delete(blurred[i]);
            Delete(textures[i]);
        }
    */
        Delete(textures[0]);
    }
}
