/*
Copyright (c) 2015 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.asset.resman;

import std.stdio;
import dlib.core.memory;
import dlib.image.io.png;
import dlib.container.aarray;
import vegan.stdfs;
import vegan.image;
import dgl.core.interfaces;
import dgl.graphics.texture;
import dgl.ui.font;

class ResourceManager: ManuallyAllocatable
{
    StdFileSystem stdfs;
    VeganImageFactory imgFac;
    AArray!Drawable drawables;
    AArray!Texture textures;
    AArray!Font fonts;
    
    this()
    {
        stdfs = New!StdFileSystem();
        imgFac = New!VeganImageFactory();
        drawables = New!(AArray!Drawable)();
        textures = New!(AArray!Texture)();
        fonts = New!(AArray!Font)();
    }
    
    Drawable addDrawable(string name, Drawable d)
    {
        drawables[name] = d;
        return d;
    }
    
    Drawable getDrawable(string name)
    {
        return drawables[name];
    }
    
    Texture getTexture(string filename)
    {
        if (filename in textures)
            return textures[filename];
            
        writefln("Loading texture %s...", filename);
        
        StdInFileStream fstrm = stdfs.openForInput(filename);
        auto res = loadPNG(fstrm, imgFac);
        Delete(fstrm);
        
        if (res[0] is null)
        {
            writeln(res[1]);
            return null;
        }
        else
        {
            auto tex = New!Texture(res[0]);
            res[0].free();
            textures[filename] = tex;
            return tex;
        }
    }
    
    Font addFont(string name, Font f)
    {
        fonts[name] = f;
        return f;
    }
    
    Font getFont(string name)
    {
        return fonts[name];
    }
    
    void freeDrawables()
    {
        foreach(i, d; drawables)
            d.free();
        drawables.free();
    }
    
    void freeTextures()
    {
        foreach(i, t; textures)
            t.free();
        textures.free();
    }
    
    void freeFonts()
    {
        foreach(i, f; fonts)
            f.free();
        fonts.free();
    }
    
    void freeContent()
    {
        freeDrawables();
        freeTextures();
        freeFonts();
    }
    
    void free()
    {
        freeContent();
    
        Delete(imgFac);
        Delete(stdfs);
        Delete(this);
    }
    
    mixin ManualModeImpl;
}
