/*
Copyright (c) 2013-2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.core.application;

private
{
    import std.stdio;
    import std.conv;
    import std.string;
    import std.process;
    import std.algorithm;

    import derelict.util.compat;
    import derelict.sdl.sdl;
    import derelict.opengl.gl;
    import derelict.opengl.glu;
    import derelict.freetype.ft;

    import dlib.image.color;
}

public
{ 
    import dgl.core.event;
    import dgl.core.layer;
}

class Application
{
    protected:
    uint videoWidth, videoHeight;
    EventManager eventManager;
    Layer[] layers;
    Color4f clearColor;

    version(Windows)
    {
        enum sharedLibSDL = "SDL.dll";
        enum sharedLibFT = "freetype.dll";
    }
    version(linux)
    {
        enum sharedLibSDL = "./libsdl.so";
        enum sharedLibFT = "./libfreetype.so";
    }

    public:
    this(uint w, uint h, string caption, GLVersion glver = GLVersion.GL12)
    {
        videoWidth = w;
        videoHeight = h;

        DerelictGL.load();
        DerelictGLU.load();
        DerelictSDL.load(sharedLibSDL);
        DerelictFT.load(sharedLibFT);

        if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_JOYSTICK) < 0)
            throw new Exception("Failed to init SDL: " ~ to!string(SDL_GetError()));

        SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
        SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_BUFFER_SIZE, 32);
        SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 16);

        environment["SDL_VIDEO_WINDOW_POS"] = "";
        environment["SDL_VIDEO_CENTERED"] = "1";

        auto screen = SDL_SetVideoMode(videoWidth, videoHeight, 0, SDL_OPENGL | SDL_RESIZABLE);
        if (screen is null)
            throw new Exception("Failed to set video mode: " ~ to!string(SDL_GetError()));

        SDL_WM_SetCaption(toStringz(caption), null);
        SDL_ShowCursor(1);

        DerelictGL.loadClassicVersions(glver); 
        DerelictGL.loadExtensions();
 
        clearColor = Color4f(0, 0, 0);

        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glEnable(GL_BLEND);
        glEnable(GL_NORMALIZE);
        glShadeModel(GL_SMOOTH);
        glAlphaFunc(GL_GREATER, 0.0);
        glEnable(GL_ALPHA_TEST);
        glEnable(GL_DEPTH_TEST);
        glDepthFunc(GL_LESS);
        glEnable(GL_CULL_FACE);

        eventManager = new EventManager(videoWidth, videoHeight);

        eventManager.bindActionToEvent(EventType.Quit, &onQuit);
        eventManager.bindActionToEvent(EventType.Resize, &onResize);
        eventManager.bindActionToEvent(EventType.KeyDown, &onKeyDown);
        eventManager.bindActionToEvent(EventType.KeyUp, &onKeyUp);
        eventManager.bindActionToEvent(EventType.MouseButtonDown, &onMouseButtonDown);
        eventManager.bindActionToEvent(EventType.MouseButtonUp, &onMouseButtonUp);
    }
    
    Layer addLayer(Layer layer)
    {
        layers ~= layer;
        sortLayersByDepth();
        return layer;
    }

    Layer addLayer3D(int depth)
    {
        Layer layer = new Layer(0, 0, videoWidth, videoHeight, LayerType.Layer3D, depth);
        layer.alignToWindow = true;
        layers ~= layer;
        sortLayersByDepth();
        return layer;
    }

    Layer addLayer2D(int depth)
    {
        Layer layer = new Layer(0, 0, videoWidth, videoHeight, LayerType.Layer2D, depth);
        layer.alignToWindow = true;
        layers ~= layer;
        sortLayersByDepth();
        return layer;
    }

    protected:

    void sortLayersByDepth()
    {
        sort!("a.depth > b.depth")(layers);
    }

    void onQuit()
    {
        eventManager.running = false;
    }

    void onResize()
    {
        SDL_Surface* screen = SDL_SetVideoMode(eventManager.window_width, 
                                               eventManager.window_height, 
                                               0, SDL_OPENGL | SDL_RESIZABLE);
        if (screen is null)
            throw new Exception("failed to set video mode: " ~ to!string(SDL_GetError()));

        foreach(layer; layers) if (layer.alignToWindow)
        {
            layer.resize(
                layer.x, 
                layer.y, 
                eventManager.window_width, 
                eventManager.window_height);
        }
    }

    void onRedraw()
    {       
        glClearColor(clearColor.r, clearColor.g, clearColor.b, clearColor.a);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        glLoadIdentity();
        
        glColor4f(1.0f, 1.0f, 1.0f, 1.0f);

        onUpdate();

        foreach(layer; layers)
        {
            layer.onUpdate(eventManager);
            layer.draw(eventManager.deltaTime);
        }

        SDL_GL_SwapBuffers();
        SDL_Delay(1);
    }

    void onKeyDown()
    {
        if (eventManager.event_key == SDLK_ESCAPE)
        {
            eventManager.running = false;
        }

        foreach(layer; layers)
            layer.onKeyDown(eventManager);
    }

    void onKeyUp()
    {
        if (eventManager.event_key == SDLK_ESCAPE)
        {
            eventManager.running = false;
        }

        foreach(layer; layers)
            layer.onKeyUp(eventManager);
    }

    void onMouseButtonDown()
    {
        foreach(layer; layers)
            layer.onMouseButtonDown(eventManager);
    }

    void onMouseButtonUp()
    {
        foreach(layer; layers)
            layer.onMouseButtonUp(eventManager);
    }

    void onUpdate()
    {
    }

    public:
    void run()
    {
        while(eventManager.running)
        {
            eventManager.update();
            onRedraw();
        }
    
        eventManager.free();
        SDL_Quit();
    }
}

