/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.core.layer;

import derelict.opengl.gl;
import derelict.opengl.glu;

import dgl.core.event;
import dgl.core.drawable;
import dgl.core.modifier;
import dgl.graphics.texture;

enum LayerType
{
    Layer2D,
    Layer3D
}

class Layer: Drawable
{
    uint x, y, width, height;
    float aspectRatio;
    LayerType type;
    bool alignToWindow = false;
    int depth = 0;

    Texture renderTarget;
    bool renderToTarget = false;

    Drawable[] drawables;
    Modifier[] modifiers;

    this(uint x, uint y, uint w, uint h, LayerType type, int depth)
    {
        this.x = x;
        this.y = y;
        this.width = w;
        this.height = h;
        this.aspectRatio = cast(float)w / cast(float)h;
        this.type = type;
        this.depth = depth;
    }

    void resize(uint x, uint y, uint w, uint h)
    {
        this.x = x;
        this.y = y;
        this.width = w;
        this.height = h;
        this.aspectRatio = cast(float)w / cast(float)h;
    }

    Texture getRenderTarget()
    {
        if (!renderTarget)
        {
            renderTarget = new Texture(width, height);
            renderToTarget = true;
        }
        return renderTarget;
    }

    override void draw(double dt)
    {
        glViewport(x, y, width, height);

        glMatrixMode(GL_PROJECTION);
        glPushMatrix();
        glLoadIdentity();
        if (type == LayerType.Layer2D)
            glOrtho(0, width, 0, height, -1, 1);
        else
            gluPerspective(60, aspectRatio, 0.1, 400.0);
        glMatrixMode(GL_MODELVIEW);

        glLoadIdentity();

        foreach(i, m; modifiers)
            m.bind(dt);
        foreach(i, d; drawables)
            d.draw(dt);
        foreach(i, m; modifiers)
            m.unbind();

        if (renderTarget && renderToTarget)
            renderTarget.copyRendered();

        glMatrixMode(GL_PROJECTION);
        glPopMatrix();
        glMatrixMode(GL_MODELVIEW);
    }

    override void free()
    {
        if (renderTarget)
            renderTarget.free();
    }

    void onUpdate(EventManager emngr) { }
    void onKeyDown(EventManager emngr) { }
    void onKeyUp(EventManager emngr) { }
    void onMouseButtonDown(EventManager emngr) { }
    void onMouseButtonUp(EventManager emngr) { }

    void addDrawable(Drawable d)
    {
        drawables ~= d;
    }

    void addModifier(Modifier m)
    {
        modifiers ~= m;
    }
}

