/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.vfs.vdir;

import std.range;

import dlib.filesystem.filesystem;
import dlib.filesystem.delegaterange;

import dgl.vfs.vfs;

class VirtualDirectory: Directory
{
    VirtualFileSystem vfs;
    size_t fsIndex = 0;
    string path;
    InputRange!DirEntry current;
    string[string] outputtedEntries;

    this(VirtualFileSystem vfs, string path)
    {
        this.vfs = vfs;
        this.path = path;
    }

    InputRange!DirEntry contents()
    {
        return new DelegateInputRange!(DirEntry)(&nextEntry);
    }

    bool nextEntry(out DirEntry entry)
    {
        while(true)
        {
            if (current is null)
            {
                auto fs = vfs.mounted[fsIndex];
                FileStat stat;
                bool exists = fs.stat(path, stat) || path == "";
                if (exists) // && stat.isDirectory
                {
                    current = fs.openDir(path).contents;
                }
                else
                {
                    current = null;
                    fsIndex++;

                    if (fsIndex >= vfs.mounted.length)
                        return false;

                    continue;
                }
            }

            if (!current.empty)
            {
                entry = current.moveFront();
                if (entry.name in outputtedEntries)
                    continue;
                else
                {
                    outputtedEntries[entry.name] = entry.name;
                    return true;
                }
            }
            else
            {
                current = null;
                fsIndex++;

                if (fsIndex >= vfs.mounted.length)
                    return false;
            }
        }
        return false;  
    }

    override void close()
    {
        vfs = null;
        fsIndex = 0;
        path = "";
        current = null;
        outputtedEntries.destroy();
    }
}

