/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.vfs.vfs;

import std.path;
import std.string;
import std.algorithm;

import dlib.core.stream;
import dlib.filesystem.filesystem;
import dlib.filesystem.local;

import dgl.vfs.localdirfs;
import dgl.vfs.vdir;
import dgl.vfs.zipfs;

public import dgl.vfs.file;

class VirtualFileSystem: ReadOnlyFileSystem
{
    ReadOnlyFileSystem[] mounted;

    void mount(ReadOnlyFileSystem fs, bool first = false)
    {
        if (first)
            mounted = fs ~ mounted;
        else
            mounted ~= fs;
    }

    void mount(string path, bool first = false)
    {
        // TODO: check if file/directory exists
        if (extension(path) == ".zip")
            mountZip(path, first);
        else
            mount(new LocalDirFileSystem(path), first);
    }

    void mountZip(string filename, bool first = false)
    {
        auto zfs = new ZipFilesystem(std.file.read(filename));
        mount(zfs, first);
    }

    bool stat(string filename, out FileStat stat)
    {
        filename = normalizePath(filename);
        foreach(fs; mounted)
        {
            FileStat s;
            if (fs.stat(filename, s))
            {
                stat = s;
                return true;
            }
        }

        return false;
    }

    InputStream openForInput(string filename)
    {
        filename = normalizePath(filename);
        foreach(fs; mounted)
        {
            FileStat s;
            if (fs.stat(filename, s))
                return fs.openForInput(filename);
        }

        return null;
    }

    Directory openDir(string path)
    {
        path = normalizePath(path);
        return new VirtualDirectory(this, path);
    }
}

string normalizePath(string path)
{
    string res = strip(path);
    if (res == "." || res == "/" || res == "./")
        res = "";
    if (res.startsWith("."))
        res = res.stripLeft('.');
    if (res.startsWith("/"))
        res = res.stripLeft('/');
    if (res.endsWith("/"))
        res = res.stripRight('/');
    return res;
}

