/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.vfs.zipfs;

import std.zip;
import std.range;
import std.algorithm;
import std.path;
import std.datetime;

import dlib.core.stream;
import dlib.filesystem.filesystem;
import dlib.filesystem.delegaterange;
import dlib.filesystem.dirrange;

import dlib.filesystem.local;

class ZipDirectory: Directory
{
    ZipFilesystem zfs;
    string prefix;
    string[] entries;
    size_t index = 0;

    this(ZipFilesystem zfs, string prefix)
    {
        this.zfs = zfs;
        this.prefix = normalize(prefix);
        this.entries = zfs.archive.directory.keys;
    }

    ~this()
    {
        close();
    }

    string normalize(string path)
    {
        string res;
        if (path == "" || path == "." || path == "/")
            res = "";
        else if (path.endsWith("/"))
            res = path;
        else
            res = path ~ "/";
        
        if (res.startsWith("."))
            res = res.stripLeft('.');
        if (res.startsWith("/"))
            res = res.stripLeft('/');
            
        return res;
    }

    bool isSubdir(string path)
    {
        if (prefix == "")
        {
            return normalize(dirName(path)) == "";
        }
        else
        {
            return dirName(path) ~ "/" == prefix;
        }
    }

    InputRange!DirEntry contents()
    {
        return new DelegateInputRange!(DirEntry)(&nextEntry);
    }

    bool nextEntry(out DirEntry entry)
    {
        while(true)
        {
            if (index >= entries.length)
                return false;
                        
            auto e = entries[index];

            index++;
            if (e.startsWith(prefix) && 
                e != prefix &&
                isSubdir(e))
            {
                bool isdir = zfs.isDirectory(e);
                entry = DirEntry(baseName(e), !isdir, isdir);
                return true;
            }
        }

        return false;
    }

    override void close()
    {
        zfs = null;
        entries = null;
        index = 0;
    }
}

class ZipFilesystem: ReadOnlyFileSystem
{
    ZipArchive archive;

    this(void[] data)
    {
        archive = new ZipArchive(data);
    }

    bool isDirectory(string filename)
    {
        return filename.endsWith("/");
    }
    
    bool exists(string filename)
    {
        if ((filename in archive.directory) !is null)
            return true;
        else if (filename == "")
            return true;
        else
            return false;
    }

    bool stat(string filename, out FileStat stat)
    {
        // Allow to omit trailing '/' for directories
        if (filename != "" && !exists(filename))
            filename ~= "/";

        // TODO: handle root filename also ("")
        if (filename == "")
        {
            stat.isDirectory = true;
            stat.isFile = false;
            // TODO: size, timestamp
            return true;
        }
        else if (exists(filename))
        {
            stat.isDirectory = isDirectory(filename);
            stat.isFile = !stat.isDirectory;
            auto m = archive.directory[filename];
            stat.sizeInBytes = m.expandedSize;
            stat.creationTimestamp = 
                stat.modificationTimestamp = 
                    DosFileTimeToSysTime(m.time);
            return true;
        }
        else
            return false;
    }

    InputStream openForInput(string filename)
    {
        if (exists(filename) && !isDirectory(filename))
        {
            auto data = archive.expand(archive.directory[filename]);
            return new ArrayStream(data, data.length);
        }
        else
            return null;
    }

    Directory openDir(string path)
    {
        return new ZipDirectory(this, path);
    }
}

