/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.ui.freeview;

import derelict.sdl.sdl;
import derelict.opengl.gl;

import dlib.image.color;

import dgl.core.drawable;
import dgl.core.application;
import dgl.core.layer;
import dgl.scene.tbcamera;

class Axes: Drawable
{
    override void draw(double dt)
    {
        glDisable(GL_LIGHTING);
        glPointSize(5.0f);
        glPushMatrix();
        glScalef(10.0f, 10.0f, 10.0f);
        glColor3f(1.0f, 0.0f, 0.0f);
        glBegin(GL_LINES);
        glVertex3f(0.0f, 0.0f, 0.0f);
        glVertex3f(1.0f, 0.0f, 0.0f);
        glEnd();
        glBegin(GL_POINTS);
        glVertex3f(1.0f, 0.0f, 0.0f);
        glEnd();
        glColor3f(0.0f, 1.0f, 0.0f);
        glBegin(GL_LINES);
        glVertex3f(0.0f, 0.0f, 0.0f);
        glVertex3f(0.0f, 1.0f, 0.0f);
        glEnd();
        glBegin(GL_POINTS);
        glVertex3f(0.0f, 1.0f, 0.0f);
        glEnd();
        glColor3f(0.0f, 0.0f, 1.0f);
        glBegin(GL_LINES);
        glVertex3f(0.0f, 0.0f, 0.0f);
        glVertex3f(0.0f, 0.0f, 1.0f);
        glEnd();
        glBegin(GL_POINTS);
        glVertex3f(0.0f, 0.0f, 1.0f);
        glEnd();
        glColor3f(1.0f, 1.0f, 1.0f);
        glBegin(GL_POINTS);
        glVertex3f(0.0f, 0.0f, 0.0f);
        glEnd();
        glPopMatrix();
        glPointSize(1.0f);
        glEnable(GL_LIGHTING);
    }

    override void free() { }
}

class FreeviewLayer: Layer
{
    int currentWindowWidth = 0;
    int currentWindowHeight = 0;

    TrackballCamera tbcamera;
    int tempMouseX = 0;
    int tempMouseY = 0;

    bool drawAxes = true;

    this(uint w, uint h)
    {
        super(0, 0, w, h, LayerType.Layer3D);

        alignToWindow = true;

        currentWindowWidth = w;
        currentWindowHeight = h;

        tbcamera = new TrackballCamera();
        tbcamera.pitch(45.0f);
        tbcamera.turn(45.0f);
        tbcamera.setZoom(20.0f);
        addModifier(tbcamera);

        auto axes = new Axes();
        addDrawable(axes);
    }

    override void onMouseButtonDown(EventManager manager)
    {
        if (manager.event_button == SDL_BUTTON_RIGHT) 
        {
            tempMouseX = manager.mouse_x;
            tempMouseY = manager.mouse_y;
            SDL_WarpMouse(cast(ushort)width/2, 
                          cast(ushort)height/2);
        }
        else if (manager.event_button == SDL_BUTTON_MIDDLE) 
        {
            tempMouseX = manager.mouse_x;
            tempMouseY = manager.mouse_y;
            SDL_WarpMouse(cast(ushort)width/2, 
                          cast(ushort)height/2);
        }
        else if (manager.event_button == SDL_BUTTON_WHEELUP) 
        {
            tbcamera.zoomSmooth(-2.0f, 16.0f);
        }
        else if (manager.event_button == SDL_BUTTON_WHEELDOWN) 
        {
            tbcamera.zoomSmooth(2.0f, 16.0f);
        }
    }

    override void onUpdate(EventManager manager)
    {
        if (manager.rmb_pressed)
        {
            float turn_m = (cast(float)(manager.window_width/2 - manager.mouse_x))/8.0f;
            float pitch_m = -(cast(float)(manager.window_height/2 - manager.mouse_y))/8.0f;
            tbcamera.pitchSmooth(pitch_m, 16.0f);
            tbcamera.turnSmooth(turn_m, 16.0f);
            SDL_WarpMouse(cast(ushort)manager.window_width/2, 
                          cast(ushort)manager.window_height/2);
            SDL_ShowCursor(0);
        }
        else if (manager.mmb_pressed || (manager.lmb_pressed && manager.key_pressed[SDLK_LSHIFT]))
        {
            float shift_x = (cast(float)(manager.window_width/2 - manager.mouse_x))/16.0f;
            float shift_y = (cast(float)(manager.window_height/2 - manager.mouse_y))/16.0f;
            tbcamera.moveSmooth(shift_y, 16.0f);
            tbcamera.strafeSmooth(-shift_x, 16.0f);
            SDL_WarpMouse(cast(ushort)manager.window_width/2, 
                          cast(ushort)manager.window_height/2);
            SDL_ShowCursor(0);
        }
        else
            SDL_ShowCursor(1);
    }
}

