/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.scene.actor;

import derelict.opengl.gl;
import derelict.opengl.glext;
import dgl.core.drawable;
import dgl.asset.animatedmodel;

class Actor: Drawable
{
    AnimatedModel model;
    ActorData data;
    ActorState state;
    
    this(AnimatedModel model)
    {
        this.model = model;
        this.data = model.genActorData();
        //model.calcBindPose();
    }

    void setAnimation(string name)
    {
        model.setAnimation(name, &state);
    }
    
    private bool buffersReady = false;
    private void generateBuffers()
    {
        glVertexPointer(3, GL_FLOAT, 0, data.vertices.ptr);
        glNormalPointer(GL_FLOAT, 0, data.normals.ptr);
        glTexCoordPointer(2, GL_FLOAT, 0, data.texcoords.ptr);
        buffersReady = true;
    }
    
    // TODO: add possibility to render in bindpose
    override void draw(double dt)
    {
        if (!buffersReady)
            generateBuffers();
            
        model.updateAnimation(dt, &data, &state);

        glPushMatrix();
        glRotatef(-90, 1, 0, 0);
        glColor3f(1, 1, 1);
        
        glEnableClientState(GL_VERTEX_ARRAY);
        glEnableClientState(GL_NORMAL_ARRAY);
        glEnableClientState(GL_TEXTURE_COORD_ARRAY);
        
        foreach(ref m; model.meshes)
        {
            if (m.material in model.materials)
                model.materials[m.material].bind(dt);
            glDrawElements(
                GL_TRIANGLES, 
                3 * m.numTriangles, 
                GL_UNSIGNED_INT, 
                &data.tris[m.firstTriangle]);
            if (m.material in model.materials)
                model.materials[m.material].unbind();
        }
        
        glDisableClientState(GL_TEXTURE_COORD_ARRAY);
        glDisableClientState(GL_NORMAL_ARRAY);
        glDisableClientState(GL_VERTEX_ARRAY);
        
        glPopMatrix();
    }
    
    override void free()
    {
    }
}
