/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.scene.scene;

import derelict.opengl.gl;
import derelict.opengl.glext;

import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.affine;
import dlib.image.image;

import dgl.core.drawable;
import dgl.graphics.material;
import dgl.graphics.texture;
import dgl.scene.mesh;
import dgl.scene.entity;

class Scene: Drawable
{
    Entity[string] entities;
    Mesh[int] meshes;
    Material[int] materials;

    Material defaultMaterial;

    int[string] matIdByName;
    int[string] meshIdByName;

    SuperImage[uint] images;
    Texture[string] textures;

    this()
    {
        defaultMaterial = new Material();
    }

    Material material(string name)
    {
        return materials[matIdByName[name]];
    }

    Mesh mesh(string name)
    {
        return meshes[meshIdByName[name]];
    }

    Entity entity(string name)
    {
        return entities[name];
    }

    Material material(int id)
    {
        return materials[id];
    }

    Mesh mesh(int id)
    {
        return meshes[id];
    }

    override void draw(double dt)
    {
        glColor3f(1, 1, 1);
        foreach(e; entities)
        {
            glPushMatrix();

            Matrix4x4f mat = Matrix4x4f.identity;
            mat *= translationMatrix(e.position);
            mat *= e.rotation.toMatrix4x4;
            mat *= scaleMatrix(e.scaling);
            glMultMatrixf(mat.arrayof.ptr);

            if (e.type == 0)
            {
                if (e.meshId in meshes)
                    drawMesh(meshes[e.meshId], dt);
                else
                    drawPoint();
            }
            else
                // TODO: other entity types
                drawPoint();

            glPopMatrix(); 
        }
    }

    void drawMesh(Mesh mesh, double dt)
    {
        foreach(fgroup; mesh.fgroups)
        {
            if (fgroup.materialIndex != -1)
            {
                if (fgroup.materialIndex in materials)
                    material(fgroup.materialIndex).bind(dt);
            }
            else
                defaultMaterial.bind(dt);

            glCallList(fgroup.displayList);

            if (fgroup.materialIndex != -1)
            {
                if (fgroup.materialIndex in materials)
                    material(fgroup.materialIndex).unbind();
            }
            else
                defaultMaterial.unbind();
        }
    }

    void drawPoint()
    {
        glDisable(GL_LIGHTING);
        glPointSize(5.0f);
        glBegin(GL_POINTS);
        glVertex3f(0, 0, 0);
        glEnd();
        glPointSize(1.0f);
        glEnable(GL_LIGHTING);
    }

    override void free() { }
}

