/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.graphics.texcombineshader;

import derelict.opengl.gl;
import derelict.opengl.glext;
import dgl.graphics.shader;
import dgl.graphics.texture;

enum: ubyte
{
    SrcTexture = 0,
    SrcPrimaryColor = 1,
    SrcPreviousColor = 2,
    OpColor = 0,
    OpAlpha = 1,
    ComReplace = 0,
    ComModulate = 1,
    ComInterpolate = 2
}

struct CombinerParam
{
    ubyte source0;
    ubyte source1;
    ubyte source2;
    ubyte operand0;
    ubyte operand1;
    ubyte operand2;
    ubyte mode;
    ubyte __dummy__;
}

final class TexCombineShader: Shader
{
    Texture[] textures;
    CombinerParam[] params;

    this() {}

    // TODO: add combiner param as an expression string,
    // e.g. C = t0 * pC; A = t0.a

    void addTextureUnit(Texture t, CombinerParam p)
    {
        // TODO: use max texture units supported by hardware
        if (textures.length < 8)
        {
            textures ~= t;
            params ~= p;
        }
    }

    override @property bool supported()
    {
        return DerelictGL.isExtensionSupported("GL_ARB_texture_env_combine");
    }

    override void bind(double delta)
    {
        foreach(i, t; textures)
        {
            glActiveTextureARB(GL_TEXTURE0_ARB + i);
            t.bind(delta);

            CombinerParam p = params[i];

            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE_ARB);

            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA_ARB, GL_ADD);

            if (p.mode == ComReplace)
                glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB_ARB, GL_REPLACE);
            else if (p.mode == ComModulate)
                glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB_ARB, GL_MODULATE);
            else if (p.mode == ComInterpolate)
                glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB_ARB, GL_INTERPOLATE_ARB);

            if (p.source0 == SrcTexture)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB_ARB, GL_TEXTURE);
            if (p.source1 == SrcTexture)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB_ARB, GL_TEXTURE);
            if (p.source2 == SrcTexture)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB_ARB, GL_TEXTURE);

            if (p.source0 == SrcPrimaryColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB_ARB, GL_PRIMARY_COLOR_ARB);
            if (p.source1 == SrcPrimaryColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB_ARB, GL_PRIMARY_COLOR_ARB);
            if (p.source2 == SrcPrimaryColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB_ARB, GL_PRIMARY_COLOR_ARB);

            if (p.source0 == SrcPreviousColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB_ARB, GL_PREVIOUS_ARB);
            if (p.source1 == SrcPreviousColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB_ARB, GL_PREVIOUS_ARB);
            if (p.source2 == SrcPreviousColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB_ARB, GL_PREVIOUS_ARB);

            if (p.operand0 == OpColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB_ARB, GL_SRC_COLOR);
            if (p.operand1 == OpColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB_ARB, GL_SRC_COLOR);
            if (p.operand2 == OpColor)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB_ARB, GL_SRC_COLOR);

            if (p.operand0 == OpAlpha)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB_ARB, GL_SRC_ALPHA);
            if (p.operand1 == OpAlpha)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB_ARB, GL_SRC_ALPHA);
            if (p.operand2 == OpAlpha)
                glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB_ARB, GL_SRC_ALPHA);
        }
    }

    override void unbind()
    {
        foreach(i, t; textures)
        {
            glActiveTextureARB(GL_TEXTURE0_ARB + i);
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
            t.unbind();
        }

        glActiveTextureARB(GL_TEXTURE0_ARB);
    }

    override void free()
    {
    }
}
